# Multistage dockerfile for reactapp frontend
# Stage 1: Build the React app
FROM node:18 AS build

# Set working directory inside the container
WORKDIR /app

# : Copy all source code
COPY . .

# Install all the project dependencies
RUN npm install

# Build the app for production
RUN npm run build

# Stage 2: Serve the app using Nginx,  Alpine is the lightweight app 
FROM nginx:alpine

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy built React app from previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]